{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-sql",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.1.jar",
          "url": "spring-boot-sql-4.0.1.jar",
          "size": 36059,
          "sha512": "c18cc8579447f9fa6c16c4b8f3464a18197626c1fe969f4ee20dbe25d556af68d5f0b01f8fe57c310c4cff9c5487eeb0426f279f7ec2c30ab8b2ab5021c24d15",
          "sha256": "f74bf3f85b01aa796e5c998154e6c1eb00df00ff8aa8bf3f4f9a583211bc9da5",
          "sha1": "222c9c9902f52b41c0d90d0d2219427dc0001098",
          "md5": "2df3e411867edd27815ad347d559079f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-sql-4.0.1.jar",
          "url": "spring-boot-sql-4.0.1.jar",
          "size": 36059,
          "sha512": "c18cc8579447f9fa6c16c4b8f3464a18197626c1fe969f4ee20dbe25d556af68d5f0b01f8fe57c310c4cff9c5487eeb0426f279f7ec2c30ab8b2ab5021c24d15",
          "sha256": "f74bf3f85b01aa796e5c998154e6c1eb00df00ff8aa8bf3f4f9a583211bc9da5",
          "sha1": "222c9c9902f52b41c0d90d0d2219427dc0001098",
          "md5": "2df3e411867edd27815ad347d559079f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.1-javadoc.jar",
          "url": "spring-boot-sql-4.0.1-javadoc.jar",
          "size": 163431,
          "sha512": "b3d93badbd6bc3fff4ab7f317c363a837342e243e953383d034a9e42c0071f755d410ee5ee20d9c7d3855cc79aa1552846c281cf8105fdefe6c65c2ebf007e70",
          "sha256": "6691446f577d84737d9ac59e8d6cae00c78d14abc3bac27e2bc85618b9ef8ea1",
          "sha1": "555c9457470942fad37fa9a83bf26514f226bee2",
          "md5": "e298b82506346a8f1b037ddd12e4f0a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-sql-4.0.1-sources.jar",
          "url": "spring-boot-sql-4.0.1-sources.jar",
          "size": 30638,
          "sha512": "70f65a227e3664d8af820647431686ca3609ca828570de881cb5bb0a5c09dafd2e34d28dbb65178a03cff2fff814d5b51171782fba075393e3a91b29803560c8",
          "sha256": "15b198a10eec3dcfa7f03ac6f17607faa74e954664449ede6259966378e2d946",
          "sha1": "29e999a4c81257a60ef414fbb61bc49f17dabe77",
          "md5": "3c4697a165c2d91202c2279f6c6e054f"
        }
      ]
    }
  ]
}
