{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.1.jar",
          "url": "spring-boot-starter-tomcat-4.0.1.jar",
          "size": 4764,
          "sha512": "0e698c581831603358ff5024290398d8d5a5a5e5e8aeb83149dca25af0d1a64abc14ccaced00a87f50f869a996aaffc183e4d99965625eb7a5963f84d0e8e6c5",
          "sha256": "fd439e7a52f66b9cfd11e7227250017bd3a198a4ddc87970bb815786c7290a12",
          "sha1": "ebf0883b5ef313119a35f74bfdcc55a816bf85a7",
          "md5": "9ae72a2227fc4ca06ed4c4f684498a4f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat-runtime",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.1.jar",
          "url": "spring-boot-starter-tomcat-4.0.1.jar",
          "size": 4764,
          "sha512": "0e698c581831603358ff5024290398d8d5a5a5e5e8aeb83149dca25af0d1a64abc14ccaced00a87f50f869a996aaffc183e4d99965625eb7a5963f84d0e8e6c5",
          "sha256": "fd439e7a52f66b9cfd11e7227250017bd3a198a4ddc87970bb815786c7290a12",
          "sha1": "ebf0883b5ef313119a35f74bfdcc55a816bf85a7",
          "md5": "9ae72a2227fc4ca06ed4c4f684498a4f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-4.0.1-javadoc.jar",
          "size": 4764,
          "sha512": "0e698c581831603358ff5024290398d8d5a5a5e5e8aeb83149dca25af0d1a64abc14ccaced00a87f50f869a996aaffc183e4d99965625eb7a5963f84d0e8e6c5",
          "sha256": "fd439e7a52f66b9cfd11e7227250017bd3a198a4ddc87970bb815786c7290a12",
          "sha1": "ebf0883b5ef313119a35f74bfdcc55a816bf85a7",
          "md5": "9ae72a2227fc4ca06ed4c4f684498a4f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-4.0.1-sources.jar",
          "url": "spring-boot-starter-tomcat-4.0.1-sources.jar",
          "size": 4764,
          "sha512": "0e698c581831603358ff5024290398d8d5a5a5e5e8aeb83149dca25af0d1a64abc14ccaced00a87f50f869a996aaffc183e4d99965625eb7a5963f84d0e8e6c5",
          "sha256": "fd439e7a52f66b9cfd11e7227250017bd3a198a4ddc87970bb815786c7290a12",
          "sha1": "ebf0883b5ef313119a35f74bfdcc55a816bf85a7",
          "md5": "9ae72a2227fc4ca06ed4c4f684498a4f"
        }
      ]
    }
  ]
}
