{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.2.jar",
          "url": "spring-webmvc-7.0.2.jar",
          "size": 1102253,
          "sha512": "827ab7c69b10fdadb7b3158e5fd8c18115ba99755825c0d4e0c4cdfb72c3a9387575ca77e8cc775216c0209060c52fe8cbf4f6ed2f711fb95093e079fce82dcd",
          "sha256": "32e6b1e3381b6caca190a159d5859bc334bba7fef84b126b513e1487e7783b41",
          "sha1": "ed0b3b7724e8cb4b47976eda5e862b3dd1ed871b",
          "md5": "776da4bbb0b1a5be8ed08f536f96348c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-7.0.2.jar",
          "url": "spring-webmvc-7.0.2.jar",
          "size": 1102253,
          "sha512": "827ab7c69b10fdadb7b3158e5fd8c18115ba99755825c0d4e0c4cdfb72c3a9387575ca77e8cc775216c0209060c52fe8cbf4f6ed2f711fb95093e079fce82dcd",
          "sha256": "32e6b1e3381b6caca190a159d5859bc334bba7fef84b126b513e1487e7783b41",
          "sha1": "ed0b3b7724e8cb4b47976eda5e862b3dd1ed871b",
          "md5": "776da4bbb0b1a5be8ed08f536f96348c"
        }
      ]
    }
  ]
}
