{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-security",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-security-4.0.1.jar",
          "url": "spring-boot-security-4.0.1.jar",
          "size": 96997,
          "sha512": "b2fa594e87cba6175f0b946ee266387a13eb31e360b3fd03cca8b4cacf948e880832e728956c93dc9d48174b111b9df224fd49bd8a87a8b8b330cfe45b8dc437",
          "sha256": "d51ed600f438e41765897fdd878c81e5136ba1ec1cd75ce72173552a569d9120",
          "sha1": "9e406a65f41f9b4d94a7373aa3743c8178f9a226",
          "md5": "4ceb04e4e6330c75fb866591765080eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-security-4.0.1.jar",
          "url": "spring-boot-security-4.0.1.jar",
          "size": 96997,
          "sha512": "b2fa594e87cba6175f0b946ee266387a13eb31e360b3fd03cca8b4cacf948e880832e728956c93dc9d48174b111b9df224fd49bd8a87a8b8b330cfe45b8dc437",
          "sha256": "d51ed600f438e41765897fdd878c81e5136ba1ec1cd75ce72173552a569d9120",
          "sha1": "9e406a65f41f9b4d94a7373aa3743c8178f9a226",
          "md5": "4ceb04e4e6330c75fb866591765080eb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-security-4.0.1-javadoc.jar",
          "url": "spring-boot-security-4.0.1-javadoc.jar",
          "size": 267458,
          "sha512": "d2e51722f92c4b8678666a4ed6f5af464e64c080e1013b7e4c69e2780479a4a493f9a774cb6d210b77454aa8e79972676719d1cbc766e3ea89a1ccdcc1811b13",
          "sha256": "fb762b63942b0eaf25ba2236ade2e51570e0a8f774da7c7eaff100aa9254cb9a",
          "sha1": "4c9a68993ad85a81091a0001c6c62c5d565d6ade",
          "md5": "134749ef604862904522032fe744d980"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-security-4.0.1-sources.jar",
          "url": "spring-boot-security-4.0.1-sources.jar",
          "size": 56590,
          "sha512": "641b24e968a387f0f699859eec5e0d0b9220aada654186ae31e278433a4104ab41ace2eea87867b3d02322dde76ad9617a41ff1137f4ad8eafd8861cb409b707",
          "sha256": "7e2e5c196d64ba70c8a5e6bba34efff427536c872f37bc64fccbfe645194f040",
          "sha1": "c0ad39f5fa8f0994b4fb94cb195a890f5a41b398",
          "md5": "306d8412a1c34f7c6b6b6e0c8cb20dce"
        }
      ]
    }
  ]
}
