{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-4.0.1.jar",
          "url": "spring-boot-loader-tools-4.0.1.jar",
          "size": 339114,
          "sha512": "dd7750ec9f0ad40e45c8fdf937090e079eb1aec102307fba1a3481a7fb0561d5f269d65fc4c9df77493a8f8c311e70ffb72f3c55b388363ffd43ab807f2d93c8",
          "sha256": "d35349d0bae0b65b87c028d9ac05fdb6e1b5dded3b903546460cbf5f46947dd6",
          "sha1": "a953c480c5918e3f5f1878a3ea576ece39d1d085",
          "md5": "e5d83122038fbe902fd7006a0b0ad890"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-4.0.1.jar",
          "url": "spring-boot-loader-tools-4.0.1.jar",
          "size": 339114,
          "sha512": "dd7750ec9f0ad40e45c8fdf937090e079eb1aec102307fba1a3481a7fb0561d5f269d65fc4c9df77493a8f8c311e70ffb72f3c55b388363ffd43ab807f2d93c8",
          "sha256": "d35349d0bae0b65b87c028d9ac05fdb6e1b5dded3b903546460cbf5f46947dd6",
          "sha1": "a953c480c5918e3f5f1878a3ea576ece39d1d085",
          "md5": "e5d83122038fbe902fd7006a0b0ad890"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-4.0.1-javadoc.jar",
          "url": "spring-boot-loader-tools-4.0.1-javadoc.jar",
          "size": 271230,
          "sha512": "cd1da64e8e6e915aa0fe0081fbe0557060b5b1d1b7870c72fb7fced8c6cf2be6897d7310c7df16e30de5ebfca80613501cb7c24ee90028c1b1744652f1780a13",
          "sha256": "9b578cbf1fc25c106273ddfad736235c47bf88a92f3af243b99a51e9b8fff4aa",
          "sha1": "606bc171f3e489f2d535344d49201dbdc5a1e7a7",
          "md5": "841bd83cbeec73b93754115ea57da2da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-4.0.1-sources.jar",
          "url": "spring-boot-loader-tools-4.0.1-sources.jar",
          "size": 68105,
          "sha512": "7d6e5adbb62a3abe5ed0256ba09f8882fa9ae3545ca524ffb883aeedbdf0fc46294f7b874b353f5a6f261b3120467088805fbf4d6ea7d25efc47f5fb7f1b3b6d",
          "sha256": "56421b97680e879a9ab9764278f542ae8d89b575fde720338e4502132687e91b",
          "sha1": "23922025c0cf819a19872eb2679647701b972de3",
          "md5": "96873a1776cee50c787cf1809723af92"
        }
      ]
    }
  ]
}
