{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-hibernate",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jpa",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "7.2.0.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-hibernate-4.0.1.jar",
          "url": "spring-boot-hibernate-4.0.1.jar",
          "size": 32054,
          "sha512": "7964f41c1c50039ed13a490ac04d16dcdbb838cbbcc2b38e1a4043da56db1ad0252c674e59472b2c340013f24842221a06aba0f21c9e7363e5be673e9e295e42",
          "sha256": "8614a2065885b99837982966bfe618421b6bafbf6dae8fbc0785288a542d843b",
          "sha1": "ae2c71638a6ec7893efb6e9b7fd83413fb418707",
          "md5": "f90d8fea8e6343a4f6d337e4309bfb02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-jpa",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "7.2.0.Final"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-orm",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-hibernate-4.0.1.jar",
          "url": "spring-boot-hibernate-4.0.1.jar",
          "size": 32054,
          "sha512": "7964f41c1c50039ed13a490ac04d16dcdbb838cbbcc2b38e1a4043da56db1ad0252c674e59472b2c340013f24842221a06aba0f21c9e7363e5be673e9e295e42",
          "sha256": "8614a2065885b99837982966bfe618421b6bafbf6dae8fbc0785288a542d843b",
          "sha1": "ae2c71638a6ec7893efb6e9b7fd83413fb418707",
          "md5": "f90d8fea8e6343a4f6d337e4309bfb02"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-hibernate-4.0.1-javadoc.jar",
          "url": "spring-boot-hibernate-4.0.1-javadoc.jar",
          "size": 140854,
          "sha512": "3be8f3d1a44d851361013a08a6f22e2b82c8e6b7f3f871af1aee8541c158c550bb2706d6f5d5dafa806c061f4fd7e4f0680718c11d7b78eb7179621e1c478aa1",
          "sha256": "a62dcbec1c83aed65adf5ddf46656c06156a7f440428e18a8b41e923be8f9738",
          "sha1": "e6c2d4c14fe69855e5d4d484aa6407573e894655",
          "md5": "dd6498086282bdca990a3c5c4aef8daa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-hibernate-4.0.1-sources.jar",
          "url": "spring-boot-hibernate-4.0.1-sources.jar",
          "size": 22848,
          "sha512": "93ccfa0274461e6c0d15aa4436178b514093ef9ee5ce336e20310ea18a9825688b663af2e2778b3a6e168aa917d5f1bb977693f97fa3175099a57994f59191f6",
          "sha256": "bbb7971764631e8cd401286b46b4f99bf1a2d7ebf905cc8b7ca1bbfc4bc09a0c",
          "sha1": "98ba8562fc73259b6cfb83c48de36eadf02548a9",
          "md5": "46c059537b99017d9aa30e301d556c70"
        }
      ]
    }
  ]
}
