{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.1.jar",
          "url": "spring-boot-autoconfigure-4.0.1.jar",
          "size": 369395,
          "sha512": "095b7f4ec43a4f4b39d478bf20dc24034f2d743df1d55ef8833f92a5292dfc41ba0c4eaf6415f0df74bd618fd3adb47884e6bfdf41fd0e65dee3fa65009358ac",
          "sha256": "5598ce8521086b5b662770b7411fc90233f393257d2e4f388d189e0ed8891272",
          "sha1": "808c34d74bbad5802bac8ce687424da4da93bb08",
          "md5": "d58228904fbdd6fc68657c4cd5d40b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.1.jar",
          "url": "spring-boot-autoconfigure-4.0.1.jar",
          "size": 369395,
          "sha512": "095b7f4ec43a4f4b39d478bf20dc24034f2d743df1d55ef8833f92a5292dfc41ba0c4eaf6415f0df74bd618fd3adb47884e6bfdf41fd0e65dee3fa65009358ac",
          "sha256": "5598ce8521086b5b662770b7411fc90233f393257d2e4f388d189e0ed8891272",
          "sha1": "808c34d74bbad5802bac8ce687424da4da93bb08",
          "md5": "d58228904fbdd6fc68657c4cd5d40b17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.1-javadoc.jar",
          "url": "spring-boot-autoconfigure-4.0.1-javadoc.jar",
          "size": 637202,
          "sha512": "60dc6ddd3415682d8db29c05d7f8607cf23f886720d1d21394d96773bec849473ebfacb6c455ac7916d2ef4e1f215ec6275cf28ac00b68832a3a8446a1adc0c8",
          "sha256": "ddae86d3a8394209a3f2dbff8bd1dad9e4667f7c26baace596ca037aa459f7bc",
          "sha1": "72014f293462d80bea76bb7f21b3f208f2ce9e49",
          "md5": "39b3ff1fa50eaf8ac5b2f5d5156b5fc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-4.0.1-sources.jar",
          "url": "spring-boot-autoconfigure-4.0.1-sources.jar",
          "size": 232596,
          "sha512": "196019dd6837e5de078cb1d85e90da8641d1479d8e491a47492d6b30fbb5cbaefbc1e8da0ee0d001c4615be8138a62cf3f3b8f09b168b44b5449f99de83bffc7",
          "sha256": "7d1c0b8162a81932c3cc58ac5c45035eb0f7a588027f23e4ab3296d77bec6e09",
          "sha1": "23b1568e70f428115fbf005c2b1c6ff1d8f22eb9",
          "md5": "8d8bb845b4099568760a1757fb649090"
        }
      ]
    }
  ]
}
