{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-web-server",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.1.jar",
          "url": "spring-boot-web-server-4.0.1.jar",
          "size": 174084,
          "sha512": "d25a7e7534dc2867d3995d6296f0366afa7ce82fdc559299c4f1d9f982bca77abfbca0f1681a0229976b0d15e6723ada00644276e3789e67f4ec03526999ae6a",
          "sha256": "f0a538e1f2d2f9cef43feb9b04b12fac4e5872d740db2eb56e362446bc4fe98c",
          "sha1": "659ce5f51c2bb7161db2811150a555a121dabd68",
          "md5": "578257dba79ab073bc230a59b50c593b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-web-server-4.0.1.jar",
          "url": "spring-boot-web-server-4.0.1.jar",
          "size": 174084,
          "sha512": "d25a7e7534dc2867d3995d6296f0366afa7ce82fdc559299c4f1d9f982bca77abfbca0f1681a0229976b0d15e6723ada00644276e3789e67f4ec03526999ae6a",
          "sha256": "f0a538e1f2d2f9cef43feb9b04b12fac4e5872d740db2eb56e362446bc4fe98c",
          "sha1": "659ce5f51c2bb7161db2811150a555a121dabd68",
          "md5": "578257dba79ab073bc230a59b50c593b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.1-javadoc.jar",
          "url": "spring-boot-web-server-4.0.1-javadoc.jar",
          "size": 411191,
          "sha512": "26298d2ee307c5b7384933f614294e07edc9256d830e02eb736fdbcc037d9222e76900a2dbe7242bca3366e45d4767f98d0d849333ad7de5a4310a966283ef99",
          "sha256": "88cef7445aa462ee5ec7293765c477164aa9a64252eb12650ae64f1b2f7fdbc7",
          "sha1": "b51810a3cde4a94ed9082b3f81ffe0648d351283",
          "md5": "f4724d3fc9e5c1f3f0e933a38c503fce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-web-server-4.0.1-sources.jar",
          "url": "spring-boot-web-server-4.0.1-sources.jar",
          "size": 129657,
          "sha512": "7406602ec960dc62673a58ade57854463297e10d3e3542f460dca10b88d34fbaf448b6e6d46a85d23d929a26d26ca9d3f6006be77386cf99adc6565f4f9fe1f7",
          "sha256": "2b4972242f850bfee701efa68d941aa23de44030038d183bc992bd134518b85b",
          "sha1": "796ba00b61997415e6bcf1335b36799c243b52e2",
          "md5": "c636fbe5540de48c4f5d06e4b8c322c8"
        }
      ]
    }
  ]
}
