{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-jdbc",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-sql",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.1.jar",
          "url": "spring-boot-jdbc-4.0.1.jar",
          "size": 201326,
          "sha512": "3f93e6c47b5c6d86d3b1fb82f521d794f89c3173f4918656909f5da53e0043945300fa79eadc80eae3ccb439faaba796dcb999e8b51d201055a7b6b1afed7a0f",
          "sha256": "db2866cc237db3983eff141f40aa409750fc8543d58cd4a38d12a918ae2a824a",
          "sha1": "662bf050fb0f5ed32f33c8e0f52df803f623e112",
          "md5": "6a3e6f3fec143eae5cbe97cc8946961a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-sql",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.1.jar",
          "url": "spring-boot-jdbc-4.0.1.jar",
          "size": 201326,
          "sha512": "3f93e6c47b5c6d86d3b1fb82f521d794f89c3173f4918656909f5da53e0043945300fa79eadc80eae3ccb439faaba796dcb999e8b51d201055a7b6b1afed7a0f",
          "sha256": "db2866cc237db3983eff141f40aa409750fc8543d58cd4a38d12a918ae2a824a",
          "sha1": "662bf050fb0f5ed32f33c8e0f52df803f623e112",
          "md5": "6a3e6f3fec143eae5cbe97cc8946961a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.1-javadoc.jar",
          "url": "spring-boot-jdbc-4.0.1-javadoc.jar",
          "size": 287704,
          "sha512": "65e8d1e1dbc5a7d77ba95cacd06e112eadb70f684999a824f118d71e4ca1cc593881aa5e6964de16f6e7d94be7a8c50ee3936b7dd4a081d16ed6167095cd6e47",
          "sha256": "dc37d241a2149c0e46bfa376b98634cb74731f34d6a59a3b5171868cac4d97f5",
          "sha1": "734ce726e393bd11e7833c829d286db5e0526eca",
          "md5": "952c84febf31d27426039b91b5d8e015"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jdbc-4.0.1-sources.jar",
          "url": "spring-boot-jdbc-4.0.1-sources.jar",
          "size": 115498,
          "sha512": "811fa9bf86f87df67bf132742931980c028df1a1e35f52159e8dcd5c913f83976ebc2b15bf16215e2c3886185cc081c061c21be3f46c3ba21b801691f9fff3c1",
          "sha256": "b0543b7b1680b4b88eb3bbd91fd676ec2968da2465215363527b1654236efdbc",
          "sha1": "f294aae689b9aa484403b15693467681c62143d1",
          "md5": "41ae604e1a6ea6780a39f23165f8d9c1"
        }
      ]
    }
  ]
}
