{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.2.jar",
          "url": "spring-security-crypto-7.0.2.jar",
          "size": 111792,
          "sha512": "9fb6e42affa3f6a3b4443e3d204a3d57737483c66b1de8c85f646bc60b0ee29665b3279728f9390200bc13a87000f5357604fc2dbde910553f422bdea72868e9",
          "sha256": "ad909c728a4a293981742e31e9f0e4c72d5800595632f402f831c5f7c737c43d",
          "sha1": "8cec3433f111e21d6349a9788a1efcf547b8db03",
          "md5": "39f1efd59135d39ab606f4a8ee9bb9f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.2.jar",
          "url": "spring-security-crypto-7.0.2.jar",
          "size": 111792,
          "sha512": "9fb6e42affa3f6a3b4443e3d204a3d57737483c66b1de8c85f646bc60b0ee29665b3279728f9390200bc13a87000f5357604fc2dbde910553f422bdea72868e9",
          "sha256": "ad909c728a4a293981742e31e9f0e4c72d5800595632f402f831c5f7c737c43d",
          "sha1": "8cec3433f111e21d6349a9788a1efcf547b8db03",
          "md5": "39f1efd59135d39ab606f4a8ee9bb9f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.2-javadoc.jar",
          "url": "spring-security-crypto-7.0.2-javadoc.jar",
          "size": 265530,
          "sha512": "adbd9deff510be2bd5087da88c10598c902430b97d8261491d63e13ba22cdea80605aefbf2aff48ee3ab825ffc47c950ce4c06556987b1f2d07d1aa11bea49c9",
          "sha256": "7a4fa266a93e1bdfb6b556ca547bdecd9a001b592677cc7a1311685efe6764c4",
          "sha1": "3a79636c19cda500bb2d0d12dbdd3977a332bb15",
          "md5": "8fc8152d36d834d22290123804852509"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-7.0.2-sources.jar",
          "url": "spring-security-crypto-7.0.2-sources.jar",
          "size": 101552,
          "sha512": "b8375c541f5052a56ae8a1dba408cc78e541f867c710f2fb44e50334f59fd2e5a35df7254f93f71db4538302eb490859927862265d7e2ea45c5370f788af7c62",
          "sha256": "d1920e17ec646945c313e7a980b47d732bd51ae2a97115dccfe0b980b254e879",
          "sha1": "424a21c6b8a819f55f3e753cd3f04159f6e1fc2f",
          "md5": "9c8bf7d21e98b0c24dc5dff9aa3c9adc"
        }
      ]
    }
  ]
}
