{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-amqp",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-amqp-4.0.1.jar",
          "url": "spring-boot-amqp-4.0.1.jar",
          "size": 91131,
          "sha512": "4ed6848108a439b7dc1b129cc038e805b3f8b64bb9aedf85a092c6e2df842602639d2bfebbeee5807c11c630dad40f3898af3b79678a3558c9fd0291aca949c3",
          "sha256": "df286a2b8e6c364d188c52fed8a133c67934dbb0b82bce16b2e1028bbd8e2f62",
          "sha1": "39c7c867066e1cad6ea3e45540a7edbfa88c1141",
          "md5": "b84a7f73eb31185715a1a1d321d64da3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-transaction",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework.amqp",
          "module": "spring-rabbit",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-amqp-4.0.1.jar",
          "url": "spring-boot-amqp-4.0.1.jar",
          "size": 91131,
          "sha512": "4ed6848108a439b7dc1b129cc038e805b3f8b64bb9aedf85a092c6e2df842602639d2bfebbeee5807c11c630dad40f3898af3b79678a3558c9fd0291aca949c3",
          "sha256": "df286a2b8e6c364d188c52fed8a133c67934dbb0b82bce16b2e1028bbd8e2f62",
          "sha1": "39c7c867066e1cad6ea3e45540a7edbfa88c1141",
          "md5": "b84a7f73eb31185715a1a1d321d64da3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-amqp-4.0.1-javadoc.jar",
          "url": "spring-boot-amqp-4.0.1-javadoc.jar",
          "size": 262358,
          "sha512": "ccf5b2c8cd8f48c8200579a3734312b1f287747a51617ac4add0d20c37ab3cd9b43bd4b4476d3ca170b08e7c0b3231e2ac76905d16e6bb7c11f2a7ed9d4ba0bb",
          "sha256": "45780faf13c532493eb2f80c818dadeb3fab0a2f1bf49effae7ee1c831e9954a",
          "sha1": "495ade51999fe0158e4231be2c0a998ebcb19297",
          "md5": "e59ffc416f7ebd9a2fcc970bf8429a5c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-amqp-4.0.1-sources.jar",
          "url": "spring-boot-amqp-4.0.1-sources.jar",
          "size": 58076,
          "sha512": "0bebf56d67483259f76b0d1d630819a647dc35c4a821e2ef79cd8497770fdebbc2e5c32e04a57c0c0fb0eeb46cadcdc3e0970e0dc9d260f8458f37262d2956f6",
          "sha256": "25db77d939da2d6f8df574e6f53a38b8f1f15cd352e3a9f460ed6cd055ddb281",
          "sha1": "9d6079149b0236e09d3fe64e4dedc72ef9c55474",
          "md5": "dcfef2998c7adbc1fc519b45559c3779"
        }
      ]
    }
  ]
}
