{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-beans",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-7.0.2.jar",
          "url": "spring-beans-7.0.2.jar",
          "size": 927127,
          "sha512": "0d51941e9a698a3ce4f34e655e4a22c37efc5200c41a99d752f3fb95bd3137bc9a86dc52c0c3ddda1223dfe91c57124ada5d9e1364fbbca6f8f35ea61d2cb65d",
          "sha256": "7ce3218b5a2172900ea9f9d791acf2cfaedcdbffcb4ef39f981daeed18411781",
          "sha1": "224739ac1b1bd96e866fb436cbcc46a7457a64a2",
          "md5": "091b6bb7aa41f79cce76ea3cada85988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-beans-7.0.2.jar",
          "url": "spring-beans-7.0.2.jar",
          "size": 927127,
          "sha512": "0d51941e9a698a3ce4f34e655e4a22c37efc5200c41a99d752f3fb95bd3137bc9a86dc52c0c3ddda1223dfe91c57124ada5d9e1364fbbca6f8f35ea61d2cb65d",
          "sha256": "7ce3218b5a2172900ea9f9d791acf2cfaedcdbffcb4ef39f981daeed18411781",
          "sha1": "224739ac1b1bd96e866fb436cbcc46a7457a64a2",
          "md5": "091b6bb7aa41f79cce76ea3cada85988"
        }
      ]
    }
  ]
}
