{
  "formatVersion": "1.1",
  "component": {
    "group": "tools.jackson.core",
    "module": "jackson-databind",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-3.0.3.jar",
          "url": "jackson-databind-3.0.3.jar",
          "size": 1860536,
          "sha512": "22f6bff435933f508fb75e2d8132d5a2b97e80a7af97e3126b99204c67e8cff05dec8d16fb1656fbb6421dc968ebbb3783a426c3addb4de2b53597ae54092797",
          "sha256": "dfbb79130910decf063125c1e693a39c5ec8fb8b478d7f39671901d47ce7f6a2",
          "sha1": "c024f05711e311341d4338cbb7905696e20921f8",
          "md5": "445adbd3b97c9638f393d8e3787ba293"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-3.0.3.jar",
          "url": "jackson-databind-3.0.3.jar",
          "size": 1860536,
          "sha512": "22f6bff435933f508fb75e2d8132d5a2b97e80a7af97e3126b99204c67e8cff05dec8d16fb1656fbb6421dc968ebbb3783a426c3addb4de2b53597ae54092797",
          "sha256": "dfbb79130910decf063125c1e693a39c5ec8fb8b478d7f39671901d47ce7f6a2",
          "sha1": "c024f05711e311341d4338cbb7905696e20921f8",
          "md5": "445adbd3b97c9638f393d8e3787ba293"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-3.0.3-javadoc.jar",
          "url": "jackson-databind-3.0.3-javadoc.jar",
          "size": 6518958,
          "sha512": "d3fa65a0af7061dfc788bc475176a34d67b8091e8898030a206d1a0ab6a7cb591fc8dcf3ab0d3eb59821a9397caf780e802fceaa3f57e5e4759de62de7774b05",
          "sha256": "da8e645f0bdf21926da955e1d4f43b719a6d48ec6e3eb62a5d4a90fff83db47a",
          "sha1": "8f3c80aaa7250a1819ee0dc01723ff77dc69b59f",
          "md5": "2a59afab7ad7aef0bdfbe55d294bc67e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-3.0.3-sources.jar",
          "url": "jackson-databind-3.0.3-sources.jar",
          "size": 1283352,
          "sha512": "bb272508d7e2d14b75c91a42499e84036a2f5fbf391def60cbd2ba1be97d15754a2ff15490e5639d8badab6302c8e32f2f67e9d79ec1b1ac32e27f0dcfbadc38",
          "sha256": "ee0dda0a11a5b391d676de9044b84aeca87fa6c469b99907dd1bc24a46772391",
          "sha1": "769fe819acc518a5192d9d9db2da5204b8cd0472",
          "md5": "deeec266e371a64d9b1ae90b4ed16c5e"
        }
      ]
    }
  ]
}
