{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.1.jar",
          "url": "spring-boot-gradle-plugin-4.0.1.jar",
          "size": 148644,
          "sha512": "249bdd50654496680004e59ab77af3f924f654fa8d28970c7a2a8d35cb938bc69e5336c90e75178d45156ca45ddaee41f985811b9b621768d690878105eef7d7",
          "sha256": "45de9af9c6a2017ffe5166cd5374c71d1ffca2e0949d90e7d6ab1a333f0303c7",
          "sha1": "8ef2e2a578a73cb244656f6cfeef74a7e5795d3f",
          "md5": "c403a92ee2973324f6b81c958461d244"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.1.jar",
          "url": "spring-boot-gradle-plugin-4.0.1.jar",
          "size": 148644,
          "sha512": "249bdd50654496680004e59ab77af3f924f654fa8d28970c7a2a8d35cb938bc69e5336c90e75178d45156ca45ddaee41f985811b9b621768d690878105eef7d7",
          "sha256": "45de9af9c6a2017ffe5166cd5374c71d1ffca2e0949d90e7d6ab1a333f0303c7",
          "sha1": "8ef2e2a578a73cb244656f6cfeef74a7e5795d3f",
          "md5": "c403a92ee2973324f6b81c958461d244"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.1-javadoc.jar",
          "url": "spring-boot-gradle-plugin-4.0.1-javadoc.jar",
          "size": 347699,
          "sha512": "2b1d4ddb0273cb7f1e329c58521ab26ebe6fb9a876d0f9f5ce1173d204a19f8ac734cb2a0529fc85c1769cd9a8bed34db42f15dd3ec00aeded80b47638e584ee",
          "sha256": "b41d54d9db8e2e9a0e1823160061e775b73e41887f341f6b9e4f0f5e115858bf",
          "sha1": "477e9e1218cd7571a0cc57915a2cf6f65fdc106e",
          "md5": "00a2d81cba89f83b9b1c6e5c6ac0a480"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-4.0.1-sources.jar",
          "url": "spring-boot-gradle-plugin-4.0.1-sources.jar",
          "size": 82389,
          "sha512": "17c4348165807c098b430699abff1d1474b36226bb020eb9548a4fe5a3dd551045a1035233c2da8aeb3e9d1f3f8b6877e0eae84cd8056574f5cf75cd6488c234",
          "sha256": "590633bbca0ae2a97c10c8ac9b494154d2a8c426545d43a71c437e843d1c6cbf",
          "sha1": "45c15566bca89811561c54d6f447ab6269a5c2ee",
          "md5": "0f3a5dcf49e9349ab585ad4a78112f2c"
        }
      ]
    }
  ]
}
