{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-webmvc",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.1.jar",
          "url": "spring-boot-starter-webmvc-4.0.1.jar",
          "size": 4749,
          "sha512": "998884347a584f9a9f34842b555dea522a5833b0ba81b171f117a500819a80955bd758eacc803cb8fc5f5e23d19cbb280fa60be15cb3656f6994d0199a30aca8",
          "sha256": "b48741541fa1f2b574f2b3dd599ac13bd0fe615b9a406d233e0223169414a265",
          "sha1": "60c3f45643c8c333a80ec51d47e07fbd1ddd4f83",
          "md5": "ecc6c943db9129160e2d24aba0d81a2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jackson",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-http-converter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-webmvc",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.1.jar",
          "url": "spring-boot-starter-webmvc-4.0.1.jar",
          "size": 4749,
          "sha512": "998884347a584f9a9f34842b555dea522a5833b0ba81b171f117a500819a80955bd758eacc803cb8fc5f5e23d19cbb280fa60be15cb3656f6994d0199a30aca8",
          "sha256": "b48741541fa1f2b574f2b3dd599ac13bd0fe615b9a406d233e0223169414a265",
          "sha1": "60c3f45643c8c333a80ec51d47e07fbd1ddd4f83",
          "md5": "ecc6c943db9129160e2d24aba0d81a2b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.1-javadoc.jar",
          "url": "spring-boot-starter-webmvc-4.0.1-javadoc.jar",
          "size": 4749,
          "sha512": "998884347a584f9a9f34842b555dea522a5833b0ba81b171f117a500819a80955bd758eacc803cb8fc5f5e23d19cbb280fa60be15cb3656f6994d0199a30aca8",
          "sha256": "b48741541fa1f2b574f2b3dd599ac13bd0fe615b9a406d233e0223169414a265",
          "sha1": "60c3f45643c8c333a80ec51d47e07fbd1ddd4f83",
          "md5": "ecc6c943db9129160e2d24aba0d81a2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-webmvc-4.0.1-sources.jar",
          "url": "spring-boot-starter-webmvc-4.0.1-sources.jar",
          "size": 4749,
          "sha512": "998884347a584f9a9f34842b555dea522a5833b0ba81b171f117a500819a80955bd758eacc803cb8fc5f5e23d19cbb280fa60be15cb3656f6994d0199a30aca8",
          "sha256": "b48741541fa1f2b574f2b3dd599ac13bd0fe615b9a406d233e0223169414a265",
          "sha1": "60c3f45643c8c333a80ec51d47e07fbd1ddd4f83",
          "md5": "ecc6c943db9129160e2d24aba0d81a2b"
        }
      ]
    }
  ]
}
