{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-jackson",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jackson-4.0.1.jar",
          "url": "spring-boot-jackson-4.0.1.jar",
          "size": 67944,
          "sha512": "4c95de9e5a0711ab6105ed1fdba3a2572bc3ae5bc2dc941a7e120c2326d01d69a36f5900b3eaf20ca6ea3a6b8844cb17f52d38b0e8c790df5fe275e2b9bdd681",
          "sha256": "4c419c426cbcb92fa8fdbf813c20a88ba950ecc78d9dfc80c515d99fdad7b5b1",
          "sha1": "245c1e71474e903bb06b6fffc018c4b2d98738c4",
          "md5": "f9fcbb137dda4821f3aa0a706380cff7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-jackson-4.0.1.jar",
          "url": "spring-boot-jackson-4.0.1.jar",
          "size": 67944,
          "sha512": "4c95de9e5a0711ab6105ed1fdba3a2572bc3ae5bc2dc941a7e120c2326d01d69a36f5900b3eaf20ca6ea3a6b8844cb17f52d38b0e8c790df5fe275e2b9bdd681",
          "sha256": "4c419c426cbcb92fa8fdbf813c20a88ba950ecc78d9dfc80c515d99fdad7b5b1",
          "sha1": "245c1e71474e903bb06b6fffc018c4b2d98738c4",
          "md5": "f9fcbb137dda4821f3aa0a706380cff7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jackson-4.0.1-javadoc.jar",
          "url": "spring-boot-jackson-4.0.1-javadoc.jar",
          "size": 177685,
          "sha512": "cc5aa56800a451f78a282a3973d9181720a16528521887b4d2de24fbd684aadd81a09fd6f2ef6ba1dbc9fb43e7d120d1963aa50599fc48a4edfa7fc78f84afc1",
          "sha256": "42e4730565897a2285805ae80962aa1de5a0735ed5e2200d604c66effd922163",
          "sha1": "c4880cbc3d07fb9cd0ddb36df38e464b48a006a1",
          "md5": "0280308cf1b95e01f9fb30dbf9a4ad37"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-jackson-4.0.1-sources.jar",
          "url": "spring-boot-jackson-4.0.1-sources.jar",
          "size": 35397,
          "sha512": "24a6df40c6edcf85c5c07778f9fa61db12e3abb2b515eb70809e1b306cee7c376f8a7e601bd56f2b54f6e3f92e4ec610f87c2ebfcfd2d3a737562180bec878de",
          "sha256": "ab84f156ffdf3189307fe62a2fa62efed1f9bcd7abcfd80dd47613c7a09131aa",
          "sha1": "ff1a800fcaf013c55fd4816bf478aec75895fe2e",
          "md5": "2b988de31320b8a9d4a91e2f922085dc"
        }
      ]
    }
  ]
}
