{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-aop",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-7.0.2.jar",
          "url": "spring-aop-7.0.2.jar",
          "size": 426260,
          "sha512": "f283af7343f586c198b8f8ea0eea248d888d1cbb7f0dcf5f989da46d82cc9a47605777a4e1d092013e02784797eff5128319a2dfcb2057e9cb4c11e7f3f0e582",
          "sha256": "bd763e6019222129aea5ac0c1261a90af3ee904e1c4b87a570175366d2f10325",
          "sha1": "25b824571d184e9d47606a62dd787bcf7c55e88e",
          "md5": "e0f1c76ae304e1d6348a7a1db2a4ba9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-aop-7.0.2.jar",
          "url": "spring-aop-7.0.2.jar",
          "size": 426260,
          "sha512": "f283af7343f586c198b8f8ea0eea248d888d1cbb7f0dcf5f989da46d82cc9a47605777a4e1d092013e02784797eff5128319a2dfcb2057e9cb4c11e7f3f0e582",
          "sha256": "bd763e6019222129aea5ac0c1261a90af3ee904e1c4b87a570175366d2f10325",
          "sha1": "25b824571d184e9d47606a62dd787bcf7c55e88e",
          "md5": "e0f1c76ae304e1d6348a7a1db2a4ba9e"
        }
      ]
    }
  ]
}
