{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.1.jar",
          "url": "spring-boot-starter-4.0.1.jar",
          "size": 4767,
          "sha512": "dc56cdfa441fc0cedb866c39fa41c80e69c244318b5813f4dc51ca2e27e1b93c9141a3f9f03eb6de6f2e5c180445ecd434878adeed11db6cac2a5e129c2b97c7",
          "sha256": "1d03d6d448c87e3fe02ee089ed3e3511370c63bd93eeae6528011cccfaaec626",
          "sha1": "775e306503c1170ba472a33a47a6549a15e7015f",
          "md5": "46d7d44713a78c635525bfb5c392bb2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-4.0.1.jar",
          "url": "spring-boot-starter-4.0.1.jar",
          "size": 4767,
          "sha512": "dc56cdfa441fc0cedb866c39fa41c80e69c244318b5813f4dc51ca2e27e1b93c9141a3f9f03eb6de6f2e5c180445ecd434878adeed11db6cac2a5e129c2b97c7",
          "sha256": "1d03d6d448c87e3fe02ee089ed3e3511370c63bd93eeae6528011cccfaaec626",
          "sha1": "775e306503c1170ba472a33a47a6549a15e7015f",
          "md5": "46d7d44713a78c635525bfb5c392bb2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.1-javadoc.jar",
          "url": "spring-boot-starter-4.0.1-javadoc.jar",
          "size": 4767,
          "sha512": "dc56cdfa441fc0cedb866c39fa41c80e69c244318b5813f4dc51ca2e27e1b93c9141a3f9f03eb6de6f2e5c180445ecd434878adeed11db6cac2a5e129c2b97c7",
          "sha256": "1d03d6d448c87e3fe02ee089ed3e3511370c63bd93eeae6528011cccfaaec626",
          "sha1": "775e306503c1170ba472a33a47a6549a15e7015f",
          "md5": "46d7d44713a78c635525bfb5c392bb2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-4.0.1-sources.jar",
          "url": "spring-boot-starter-4.0.1-sources.jar",
          "size": 4767,
          "sha512": "dc56cdfa441fc0cedb866c39fa41c80e69c244318b5813f4dc51ca2e27e1b93c9141a3f9f03eb6de6f2e5c180445ecd434878adeed11db6cac2a5e129c2b97c7",
          "sha256": "1d03d6d448c87e3fe02ee089ed3e3511370c63bd93eeae6528011cccfaaec626",
          "sha1": "775e306503c1170ba472a33a47a6549a15e7015f",
          "md5": "46d7d44713a78c635525bfb5c392bb2e"
        }
      ]
    }
  ]
}
