{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-core",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.2.jar",
          "url": "spring-core-7.0.2.jar",
          "size": 2012955,
          "sha512": "82a02f0af0a20e73fc03e9afe51b87a038fc5f792292bfed8ce37c26b42ec6e27afcedbdaf23d27bdf7d8514ca5fb72b26fac1dc4b80291009b42f3869339257",
          "sha256": "4d0ceaa52d33483b2442cada981bba8a8b0227b969bdabfffc5b128e1e02f9bc",
          "sha1": "92b5608685a6212fe2ce3565bc1bf660505560c7",
          "md5": "15551a52baa8a51cba039e2a87e138c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-core-7.0.2.jar",
          "url": "spring-core-7.0.2.jar",
          "size": 2012955,
          "sha512": "82a02f0af0a20e73fc03e9afe51b87a038fc5f792292bfed8ce37c26b42ec6e27afcedbdaf23d27bdf7d8514ca5fb72b26fac1dc4b80291009b42f3869339257",
          "sha256": "4d0ceaa52d33483b2442cada981bba8a8b0227b969bdabfffc5b128e1e02f9bc",
          "sha1": "92b5608685a6212fe2ce3565bc1bf660505560c7",
          "md5": "15551a52baa8a51cba039e2a87e138c7"
        }
      ]
    }
  ]
}
