{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-validation",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-validation",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.1.jar",
          "url": "spring-boot-starter-validation-4.0.1.jar",
          "size": 4767,
          "sha512": "2cfb2fa3482c9d224170c21abe5c0bf4f78d8867f733669eb25e8c7ac51e134956f4b6d7fd5c2053e9b84cb006375ce0d7ffa12ff2d7e909e5fb02d60d4591f8",
          "sha256": "9aa80d87c65c776b105a7665a391b2d69b3154832aeda4bf9f227619d3d4c806",
          "sha1": "a65f750c574eb608c6df23b076dee84fa4a26aff",
          "md5": "6b0bc93f8828a3291d136887491b9188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-validation",
          "version": {
            "requires": "4.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.1.jar",
          "url": "spring-boot-starter-validation-4.0.1.jar",
          "size": 4767,
          "sha512": "2cfb2fa3482c9d224170c21abe5c0bf4f78d8867f733669eb25e8c7ac51e134956f4b6d7fd5c2053e9b84cb006375ce0d7ffa12ff2d7e909e5fb02d60d4591f8",
          "sha256": "9aa80d87c65c776b105a7665a391b2d69b3154832aeda4bf9f227619d3d4c806",
          "sha1": "a65f750c574eb608c6df23b076dee84fa4a26aff",
          "md5": "6b0bc93f8828a3291d136887491b9188"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.1-javadoc.jar",
          "url": "spring-boot-starter-validation-4.0.1-javadoc.jar",
          "size": 4767,
          "sha512": "2cfb2fa3482c9d224170c21abe5c0bf4f78d8867f733669eb25e8c7ac51e134956f4b6d7fd5c2053e9b84cb006375ce0d7ffa12ff2d7e909e5fb02d60d4591f8",
          "sha256": "9aa80d87c65c776b105a7665a391b2d69b3154832aeda4bf9f227619d3d4c806",
          "sha1": "a65f750c574eb608c6df23b076dee84fa4a26aff",
          "md5": "6b0bc93f8828a3291d136887491b9188"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-validation-4.0.1-sources.jar",
          "url": "spring-boot-starter-validation-4.0.1-sources.jar",
          "size": 4767,
          "sha512": "2cfb2fa3482c9d224170c21abe5c0bf4f78d8867f733669eb25e8c7ac51e134956f4b6d7fd5c2053e9b84cb006375ce0d7ffa12ff2d7e909e5fb02d60d4591f8",
          "sha256": "9aa80d87c65c776b105a7665a391b2d69b3154832aeda4bf9f227619d3d4c806",
          "sha1": "a65f750c574eb608c6df23b076dee84fa4a26aff",
          "md5": "6b0bc93f8828a3291d136887491b9188"
        }
      ]
    }
  ]
}
