{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-validation",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "9.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-validation-4.0.1.jar",
          "url": "spring-boot-validation-4.0.1.jar",
          "size": 15261,
          "sha512": "cd8d574b4e8b6521a5d2a4cbe2a54a781356736dc6c56f6fb691aff0d18ba9c0092b51eaad0af85e42c61ad46cf12fe8c89b4ec785a7d0ec7cad4475dace5632",
          "sha256": "303813d2aa7d0789c3517fc316d4d95734f697ccd89be8da3a1dae46eabde0c9",
          "sha1": "51922ef1ef8049c95e2749d2a11bcb60d59c3ecf",
          "md5": "3ae557f80fa85871efcd3f131fcb75f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.hibernate.validator",
          "module": "hibernate-validator",
          "version": {
            "requires": "9.0.1.Final"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-validation-4.0.1.jar",
          "url": "spring-boot-validation-4.0.1.jar",
          "size": 15261,
          "sha512": "cd8d574b4e8b6521a5d2a4cbe2a54a781356736dc6c56f6fb691aff0d18ba9c0092b51eaad0af85e42c61ad46cf12fe8c89b4ec785a7d0ec7cad4475dace5632",
          "sha256": "303813d2aa7d0789c3517fc316d4d95734f697ccd89be8da3a1dae46eabde0c9",
          "sha1": "51922ef1ef8049c95e2749d2a11bcb60d59c3ecf",
          "md5": "3ae557f80fa85871efcd3f131fcb75f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-validation-4.0.1-javadoc.jar",
          "url": "spring-boot-validation-4.0.1-javadoc.jar",
          "size": 114068,
          "sha512": "2ba0e9a6a934026d46205816cd6e739bdfd83f717e8d66d9cf9577b483363672afffb30b9fc87b25511814c0d93b614a7c25bff74a7b2969530724f5d713b3e8",
          "sha256": "c40439df89e96097da8f1381022476c0f3c12c63cee60785dc79a556d1a930fc",
          "sha1": "07f28a3f16c06687b7f5d3bfb51822a775a56a4a",
          "md5": "7a4a8889d0046c2b47827ec554db8017"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-validation-4.0.1-sources.jar",
          "url": "spring-boot-validation-4.0.1-sources.jar",
          "size": 13880,
          "sha512": "07186c54ea382bdd22e76a97ca97bb54fc8480062a577837f8f8f314a5542821ae9796033998e5bb2aa05b1efe632cbfb6e7c3182e8ae1cb70ff9ddfba7d6d9b",
          "sha256": "16d1336f740f5619ff45904e42927177d3978e8665e5f620483e96d082fd93b4",
          "sha1": "0af06abda780d6497f09fd04c944e7e574ac71c0",
          "md5": "db8bbf5855ed791ad50d35aa4aa681c0"
        }
      ]
    }
  ]
}
