{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-expression",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-7.0.2.jar",
          "url": "spring-expression-7.0.2.jar",
          "size": 322605,
          "sha512": "61e38f7695db10c89a349d80d9a738c44198874efab0631c2bf7c0a130ab8811a41a579e89bdafe1cad72fe3309767fa4830323d3cddb32d5bcf8ff7caef14c0",
          "sha256": "2e1596cfc15322329c655805c2dd01a3f2a1d1145f8f91cac2d4b0f7de284f4a",
          "sha1": "692338c5c7eaeeeba4f0919b54216c1bf9fbee04",
          "md5": "41497d8d9f3899e500b38c165d7d7695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-expression-7.0.2.jar",
          "url": "spring-expression-7.0.2.jar",
          "size": 322605,
          "sha512": "61e38f7695db10c89a349d80d9a738c44198874efab0631c2bf7c0a130ab8811a41a579e89bdafe1cad72fe3309767fa4830323d3cddb32d5bcf8ff7caef14c0",
          "sha256": "2e1596cfc15322329c655805c2dd01a3f2a1d1145f8f91cac2d4b0f7de284f4a",
          "sha1": "692338c5c7eaeeeba4f0919b54216c1bf9fbee04",
          "md5": "41497d8d9f3899e500b38c165d7d7695"
        }
      ]
    }
  ]
}
