{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.amqp",
    "module": "spring-amqp",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-4.0.1.jar",
          "url": "spring-amqp-4.0.1.jar",
          "size": 192159,
          "sha512": "983e908631e901bb74512334f90ff12652b2e48f21cd124ce1eea678597bbe6fee7e61289bb7154189187cb9b18e7c85a3bb4b865e5f9dadffd48a3949013828",
          "sha256": "e2ea1975cc5de4657752583306722857d1d0a5401e2f6cdda1da087ca4fa6187",
          "sha1": "1dd62f32bb4f024fd3aec04a3e7164c8fade9012",
          "md5": "1e177d62c923124e0801f0da5a6511ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-4.0.1.jar",
          "url": "spring-amqp-4.0.1.jar",
          "size": 192159,
          "sha512": "983e908631e901bb74512334f90ff12652b2e48f21cd124ce1eea678597bbe6fee7e61289bb7154189187cb9b18e7c85a3bb4b865e5f9dadffd48a3949013828",
          "sha256": "e2ea1975cc5de4657752583306722857d1d0a5401e2f6cdda1da087ca4fa6187",
          "sha1": "1dd62f32bb4f024fd3aec04a3e7164c8fade9012",
          "md5": "1e177d62c923124e0801f0da5a6511ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-amqp-4.0.1-javadoc.jar",
          "url": "spring-amqp-4.0.1-javadoc.jar",
          "size": 4703367,
          "sha512": "da42d5b4cb2f0fb1eceea13ead640ce513e85bc8c48cbbbd5a5606fb538f457023c2873f5eb6653f5a02c146c7fa9988a867ae8e82d7a5120fdd8b1be0bcb3fd",
          "sha256": "1728436f3804ee286c2511a5eaa3324e296cb9d181b59a4e1cf15de92a9e7814",
          "sha1": "30bc382bd29d4da83585644ddf5d6de33550c25a",
          "md5": "94826cd0c7aa19438883ab26ed6d04e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-amqp-4.0.1-sources.jar",
          "url": "spring-amqp-4.0.1-sources.jar",
          "size": 159487,
          "sha512": "2a6b331081a2da6d627df0189265eadfe01c33af4f86ba408311f2dfd64e1e71daa1995c40c2b38b36527fc18a9c1773725f66d2840cbe1ff386fbda28754e3b",
          "sha256": "89ce17a4dde80fb6eda733acbabf0a474f2c622464e9c0e6c7bd76abaf3509c1",
          "sha1": "1171aaf8416d0bf2db743d3fa176e49483717c6e",
          "md5": "fa953577453039b94212bef2270d2e3e"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "3.0.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-4.0.1.jar",
          "url": "spring-amqp-4.0.1.jar",
          "size": 192159,
          "sha512": "983e908631e901bb74512334f90ff12652b2e48f21cd124ce1eea678597bbe6fee7e61289bb7154189187cb9b18e7c85a3bb4b865e5f9dadffd48a3949013828",
          "sha256": "e2ea1975cc5de4657752583306722857d1d0a5401e2f6cdda1da087ca4fa6187",
          "sha1": "1dd62f32bb4f024fd3aec04a3e7164c8fade9012",
          "md5": "1e177d62c923124e0801f0da5a6511ca"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-amqp-optional",
          "version": "4.0.1"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-oxm",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "tools.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "3.0.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-amqp-4.0.1.jar",
          "url": "spring-amqp-4.0.1.jar",
          "size": 192159,
          "sha512": "983e908631e901bb74512334f90ff12652b2e48f21cd124ce1eea678597bbe6fee7e61289bb7154189187cb9b18e7c85a3bb4b865e5f9dadffd48a3949013828",
          "sha256": "e2ea1975cc5de4657752583306722857d1d0a5401e2f6cdda1da087ca4fa6187",
          "sha1": "1dd62f32bb4f024fd3aec04a3e7164c8fade9012",
          "md5": "1e177d62c923124e0801f0da5a6511ca"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-amqp-optional",
          "version": "4.0.1"
        }
      ]
    }
  ]
}
