{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.amqp",
    "module": "spring-rabbit",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.rabbitmq",
          "module": "amqp-client",
          "version": {
            "requires": "5.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-4.0.1.jar",
          "url": "spring-rabbit-4.0.1.jar",
          "size": 663385,
          "sha512": "a1b3be17c4cd3ab5c9ea8d6e6b89b3ec55ad2cef1db2180a48b9dc2bb106316f8c490de4b696e21010c4df52057266ded13af75afbbd5a9e86de79f862febb45",
          "sha256": "c76eb47f4a5b5df5c022efcae52743c006ae728fc2056da5dc42dd1317c1e6ea",
          "sha1": "1dae1a474b7c01ded966ece8e4b64db67b65264d",
          "md5": "59f1f76b33046eb35079bb73ecf383d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.amqp",
          "module": "spring-amqp",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.rabbitmq",
          "module": "amqp-client",
          "version": {
            "requires": "5.27.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-4.0.1.jar",
          "url": "spring-rabbit-4.0.1.jar",
          "size": 663385,
          "sha512": "a1b3be17c4cd3ab5c9ea8d6e6b89b3ec55ad2cef1db2180a48b9dc2bb106316f8c490de4b696e21010c4df52057266ded13af75afbbd5a9e86de79f862febb45",
          "sha256": "c76eb47f4a5b5df5c022efcae52743c006ae728fc2056da5dc42dd1317c1e6ea",
          "sha1": "1dae1a474b7c01ded966ece8e4b64db67b65264d",
          "md5": "59f1f76b33046eb35079bb73ecf383d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-rabbit-4.0.1-javadoc.jar",
          "url": "spring-rabbit-4.0.1-javadoc.jar",
          "size": 5301812,
          "sha512": "cfa1e322f6857b45f1abe9b04c4de5922f84be9957b151dc0bf6c0eb6d0d1efe697fafe625b0dc440366ec3e5a574a03763bfc05374ce500a2fcec13ea6af56d",
          "sha256": "755545a43c217378c96ad3db37d83f501b834225ad7b1dc1f6eb93ba5af281f8",
          "sha1": "959263e40f3c5980077d43fda689a6c3ed0f4a47",
          "md5": "71c22bffc10989710318c5434a828649"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-rabbit-4.0.1-sources.jar",
          "url": "spring-rabbit-4.0.1-sources.jar",
          "size": 450689,
          "sha512": "2f3b04b58c9b7a96b3c27966996d9fe076fbd483a5406ccb1228222f21132d1960c28062402c9fac767d0c375c7a7023faa46f7a91bb3fab597f7e1c9c13611d",
          "sha256": "4e0863f13ca0867873c6a7e4e8c9a3b7359193b2a99c7c90bbd84d09149d9c55",
          "sha1": "fc6fcf7f3508e7b37d1e91fa1920a42419e2194b",
          "md5": "fff8a8c59880a21d05891fe77a430c95"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.22"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-pool2",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-4.0.1.jar",
          "url": "spring-rabbit-4.0.1.jar",
          "size": 663385,
          "sha512": "a1b3be17c4cd3ab5c9ea8d6e6b89b3ec55ad2cef1db2180a48b9dc2bb106316f8c490de4b696e21010c4df52057266ded13af75afbbd5a9e86de79f862febb45",
          "sha256": "c76eb47f4a5b5df5c022efcae52743c006ae728fc2056da5dc42dd1317c1e6ea",
          "sha1": "1dae1a474b7c01ded966ece8e4b64db67b65264d",
          "md5": "59f1f76b33046eb35079bb73ecf383d5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-rabbit-optional",
          "version": "4.0.1"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webflux",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.5.1"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.22"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.25.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.16.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-pool2",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-rabbit-4.0.1.jar",
          "url": "spring-rabbit-4.0.1.jar",
          "size": 663385,
          "sha512": "a1b3be17c4cd3ab5c9ea8d6e6b89b3ec55ad2cef1db2180a48b9dc2bb106316f8c490de4b696e21010c4df52057266ded13af75afbbd5a9e86de79f862febb45",
          "sha256": "c76eb47f4a5b5df5c022efcae52743c006ae728fc2056da5dc42dd1317c1e6ea",
          "sha1": "1dae1a474b7c01ded966ece8e4b64db67b65264d",
          "md5": "59f1f76b33046eb35079bb73ecf383d5"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.amqp",
          "name": "spring-rabbit-optional",
          "version": "4.0.1"
        }
      ]
    }
  ]
}
