{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-mail",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "jakarta.mail",
          "module": "jakarta.mail-api",
          "version": {
            "requires": "2.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-mail-4.0.1.jar",
          "url": "spring-boot-mail-4.0.1.jar",
          "size": 20777,
          "sha512": "0831948abe9b20feed20c1eb3b5ae50133ef15b76084b77d661286c031279fc99ee24177586ebbcceeef6d7034b103989c8fce7609731bb655adcd1c2bbf55ae",
          "sha256": "b3478134b7192fe4a7f8f6bd16938f913d31c1b061c1385f2823e98ea45a6eaa",
          "sha1": "7d3dbd6158331f529cccfd0b5fe3e766e5f1ada7",
          "md5": "fdd01b97c71def62d5b4e735a0ea993d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "jakarta.mail",
          "module": "jakarta.mail-api",
          "version": {
            "requires": "2.1.5"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "angus-mail",
          "version": {
            "requires": "2.0.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-mail-4.0.1.jar",
          "url": "spring-boot-mail-4.0.1.jar",
          "size": 20777,
          "sha512": "0831948abe9b20feed20c1eb3b5ae50133ef15b76084b77d661286c031279fc99ee24177586ebbcceeef6d7034b103989c8fce7609731bb655adcd1c2bbf55ae",
          "sha256": "b3478134b7192fe4a7f8f6bd16938f913d31c1b061c1385f2823e98ea45a6eaa",
          "sha1": "7d3dbd6158331f529cccfd0b5fe3e766e5f1ada7",
          "md5": "fdd01b97c71def62d5b4e735a0ea993d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-mail-4.0.1-javadoc.jar",
          "url": "spring-boot-mail-4.0.1-javadoc.jar",
          "size": 127558,
          "sha512": "59c05329db5a3d4c9bc5a7c341b31e7a090f62dbe6eafbbfbf02532a77ae9e37f2b99fc016754b6e4f90fb336795070b18c6900d6e36df611150ae33a695ae37",
          "sha256": "ab10d7b6f8951f2694a5cb19897b1651dbb6d009cacddb47874cb795ddd2bea0",
          "sha1": "b0283c1340209eb9d9332052adb0ec06e1404a44",
          "md5": "f442ef5e74c72183e86628975b5f04b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-mail-4.0.1-sources.jar",
          "url": "spring-boot-mail-4.0.1-sources.jar",
          "size": 16443,
          "sha512": "24f3be090e0713c73ef1c55656b0e6b21e3328b2158a210b920b7e0b457ff9a29384f17cb170ee03fe177aa121326583b87112f6e20736530d6d53d23130234d",
          "sha256": "0fddada890a29f0a208793d95fecbf3a0db9a7ddd8755eb15c0f8bbc6f513aad",
          "sha1": "73a3ec129fc7346297a9737f6b283942a0e5cc09",
          "md5": "1e164a8b31b78ecda28deb80bb79a070"
        }
      ]
    }
  ]
}
