{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat-runtime",
    "version": "4.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.1.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.1.jar",
          "size": 4745,
          "sha512": "7adcade87dfda9ec1c8d489052ccaa8aee2508a8f4bc7d7c2058b5270603119d30ac9d1178839e3ac6fb47c1b48f492bb504e0c4899c64347e88618a5999b318",
          "sha256": "029a4b3e6f2d2db29359b7743027fcf8b1e0a87cef17cf0644560f6da831c771",
          "sha1": "ce0f7d5cb75fbfcdbc839d0aeee62ce38f8ee58c",
          "md5": "554727caeb03e5ab14cd7b40a7e0eae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-tomcat",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-web-server",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "11.0.15"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "11.0.15"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.1.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.1.jar",
          "size": 4745,
          "sha512": "7adcade87dfda9ec1c8d489052ccaa8aee2508a8f4bc7d7c2058b5270603119d30ac9d1178839e3ac6fb47c1b48f492bb504e0c4899c64347e88618a5999b318",
          "sha256": "029a4b3e6f2d2db29359b7743027fcf8b1e0a87cef17cf0644560f6da831c771",
          "sha1": "ce0f7d5cb75fbfcdbc839d0aeee62ce38f8ee58c",
          "md5": "554727caeb03e5ab14cd7b40a7e0eae1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.1-javadoc.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.1-javadoc.jar",
          "size": 4745,
          "sha512": "7adcade87dfda9ec1c8d489052ccaa8aee2508a8f4bc7d7c2058b5270603119d30ac9d1178839e3ac6fb47c1b48f492bb504e0c4899c64347e88618a5999b318",
          "sha256": "029a4b3e6f2d2db29359b7743027fcf8b1e0a87cef17cf0644560f6da831c771",
          "sha1": "ce0f7d5cb75fbfcdbc839d0aeee62ce38f8ee58c",
          "md5": "554727caeb03e5ab14cd7b40a7e0eae1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-runtime-4.0.1-sources.jar",
          "url": "spring-boot-starter-tomcat-runtime-4.0.1-sources.jar",
          "size": 4745,
          "sha512": "7adcade87dfda9ec1c8d489052ccaa8aee2508a8f4bc7d7c2058b5270603119d30ac9d1178839e3ac6fb47c1b48f492bb504e0c4899c64347e88618a5999b318",
          "sha256": "029a4b3e6f2d2db29359b7743027fcf8b1e0a87cef17cf0644560f6da831c771",
          "sha1": "ce0f7d5cb75fbfcdbc839d0aeee62ce38f8ee58c",
          "md5": "554727caeb03e5ab14cd7b40a7e0eae1"
        }
      ]
    }
  ]
}
