{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-messaging",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.2.jar",
          "url": "spring-messaging-7.0.2.jar",
          "size": 611581,
          "sha512": "c9e8b92d60fe7acb1c1a6906a7dcca93c7c457921bc045cf718e4d72f1f98fb7cb2169170238a1fffd744296e867a49c6a093689263815e2115585a18fd84d4e",
          "sha256": "85325abe44a21e28c8e15c6af2cecb6ccbfefc3f7585191edc1a80af3a09c6ba",
          "sha1": "f4f24e27370cc6361829f25e167ee00ea8a6144f",
          "md5": "7251a3fcf826a2f3265febd1d7dcc763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-messaging-7.0.2.jar",
          "url": "spring-messaging-7.0.2.jar",
          "size": 611581,
          "sha512": "c9e8b92d60fe7acb1c1a6906a7dcca93c7c457921bc045cf718e4d72f1f98fb7cb2169170238a1fffd744296e867a49c6a093689263815e2115585a18fd84d4e",
          "sha256": "85325abe44a21e28c8e15c6af2cecb6ccbfefc3f7585191edc1a80af3a09c6ba",
          "sha1": "f4f24e27370cc6361829f25e167ee00ea8a6144f",
          "md5": "7251a3fcf826a2f3265febd1d7dcc763"
        }
      ]
    }
  ]
}
