{
  "formatVersion": "1.1",
  "component": {
    "group": "tools.jackson.core",
    "module": "jackson-core",
    "version": "3.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-3.0.3.jar",
          "url": "jackson-core-3.0.3.jar",
          "size": 594167,
          "sha512": "b2b5e9ba2bf2075f6b569fda67dac0e2df73702634ffd466654c977bd2d758ec4732cf4b721b3194ef5819b25f23f3e1b60826ec6be3863e5583e19d16d783d6",
          "sha256": "4149bb2b3bbffb5339089174e26f454081e6a01a104d24b22f78a16b948799eb",
          "sha1": "d208ec73d6a17667a0462cfc3237076a087bc936",
          "md5": "5abfa2ee36fa2833fe40521f851dc08a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-core-3.0.3.jar",
          "url": "jackson-core-3.0.3.jar",
          "size": 594167,
          "sha512": "b2b5e9ba2bf2075f6b569fda67dac0e2df73702634ffd466654c977bd2d758ec4732cf4b721b3194ef5819b25f23f3e1b60826ec6be3863e5583e19d16d783d6",
          "sha256": "4149bb2b3bbffb5339089174e26f454081e6a01a104d24b22f78a16b948799eb",
          "sha1": "d208ec73d6a17667a0462cfc3237076a087bc936",
          "md5": "5abfa2ee36fa2833fe40521f851dc08a"
        }
      ]
    }
  ]
}
