{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-web",
    "version": "7.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-7.0.2.jar",
          "url": "spring-web-7.0.2.jar",
          "size": 2192849,
          "sha512": "7fc8401474f628c6c0ac532dd6f5cb702903f8df833c79b8825329cb040ed6764ccb513736818b0f60577aa79290ee3987011d25a0df7e60f74ade7ae7aac003",
          "sha256": "49767bf0effe8d4ebaaf16453ff1bffc4478f7328a687313811e56d5140feca5",
          "sha1": "fc1f3eec8e102b896b06c0082bf4d08486e091d3",
          "md5": "656e35517710f8c028196b79cecbb96a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "7.0.2"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.16.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-web-7.0.2.jar",
          "url": "spring-web-7.0.2.jar",
          "size": 2192849,
          "sha512": "7fc8401474f628c6c0ac532dd6f5cb702903f8df833c79b8825329cb040ed6764ccb513736818b0f60577aa79290ee3987011d25a0df7e60f74ade7ae7aac003",
          "sha256": "49767bf0effe8d4ebaaf16453ff1bffc4478f7328a687313811e56d5140feca5",
          "sha1": "fc1f3eec8e102b896b06c0082bf4d08486e091d3",
          "md5": "656e35517710f8c028196b79cecbb96a"
        }
      ]
    }
  ]
}
